// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnLog } from "./TurnLog";

export type AcceptedReply = { revision: number, pending_teams: Array<number>, resolved_turn: TurnLog | null, };
