// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SimCommand } from "./SimCommand";

export type CommandEnvelope = { command_id: number, expected_revision: number, command: SimCommand, };
