// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcceptedReply } from "./AcceptedReply";
import type { RejectedReply } from "./RejectedReply";

export type CommandReply = { "status": "accepted" } & AcceptedReply | { "status": "rejected" } & RejectedReply;
