// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellRef } from "./CellRef";

export type LootView = { id: number, pos: CellRef, value: number, claimed: boolean, };
