// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RejectReason } from "./RejectReason";

export type RejectedReply = { current_revision: number, reason: RejectReason, detail: string | null, };
