// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SimConfig = { grid_radius: number, visible_radius: number, passive_decay: number, passive_strength: number, active_strength: number, active_cooldown: number, belief_decay_rate: number, team_count: number, min_units_per_team: number, max_units_per_team: number, exit_points_count: number, max_loot: number, };
