// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TeamTurnIntent } from "./TeamTurnIntent";

export type SimCommand = { "type": "submit_team_intent", team_id: number, intent: TeamTurnIntent, };
