// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BeliefUpdate } from "./BeliefUpdate";
import type { CellRef } from "./CellRef";
import type { DecisionIntent } from "./DecisionIntent";
import type { ScanMode } from "./ScanMode";
import type { WeaponType } from "./WeaponType";

export type SimEvent = { "type": "turn_start", turn: number, } | { "type": "scan_result", team_id: number, mode: ScanMode, updates: Array<BeliefUpdate>, } | { "type": "unit_decision", unit_id: number, intent: DecisionIntent, reason: string, target: CellRef | null, } | { "type": "unit_moved", unit_id: number, from: CellRef, to: CellRef, movement_range: number, } | { "type": "attack", attacker_id: number, target_id: number, weapon_type: WeaponType, weapon_range: number, base_damage: number, hit: boolean, damage: number, } | { "type": "unit_destroyed", unit_id: number, } | { "type": "loot_recovered", unit_id: number, loot_id: number, value: number, } | { "type": "loot_dropped", unit_id: number, loot_id: number, value: number, pos: CellRef, } | { "type": "unit_exited", unit_id: number, exit_id: number, } | { "type": "active_scan_ping", unit_id: number, center: CellRef, };
