// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TeamColor } from "./TeamColor";

export type TeamView = { id: number, name: string, color: TeamColor, };
