// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExitPointView } from "./ExitPointView";
import type { LootView } from "./LootView";
import type { SimEvent } from "./SimEvent";
import type { TeamBeliefView } from "./TeamBeliefView";
import type { TeamView } from "./TeamView";
import type { UnitView } from "./UnitView";

export type TurnLog = { turn: number, events: Array<SimEvent>, units: Array<UnitView>, loot: Array<LootView>, beliefs: Array<TeamBeliefView>, teams: Array<TeamView>, exits: Array<ExitPointView>, grid_radius: number, };
