// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UnitIntent = { "type": "hold", unit_id: number, } | { "type": "move", unit_id: number, to_cell_id: number, };
