// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiArchetype } from "./AiArchetype";
import type { CellRef } from "./CellRef";
import type { WeaponType } from "./WeaponType";

export type UnitView = { id: number, team_id: number, archetype: AiArchetype, hp: number, pos: CellRef, attack_range: number, attack_damage: number, movement_range: number, weapon_type: WeaponType, inventory_slots: number, inventory_used: number, visible_radius: number, has_active_scan: boolean, };
